######################################################################################################
###                                                                                                ###
###   FlatMe - Plot Plugin by Steven Meisberger (Sigmaroot Administration)                         ###
###                                                                                                ###
###     Version:     1.0                                                                           ###
###     File:        Basic Configuration                                                           ###
###                                                                                                ###
###     Date:        01.11.2015                                                                    ###
###                                                                                                ###
######################################################################################################
language: de