######################################################################################################
###                                                                                                ###
###   FlatMe - Plot Plugin by Steven Meisberger (Sigmaroot Administration)                         ###
###                                                                                                ###
###     Version:     1.8.5                                                                         ###
###     File:        Basic Configuration                                                           ###
###                                                                                                ###
###     Date:        16.11.2015                                                                    ###
###                                                                                                ###
######################################################################################################

###  Localization: text_**.yml                           ###
###  Default: en                                         ###
language: en
###  Worldname for plotarea                              ###
###  Default: world                                      ###
world: world
###  Radius of the plotarea (for each direction)         ###
###  Default: 3                                          ###
radius: 3
###  Plotsize AxA blocks                                 ###
###  Default: 50                                         ###
plotSize: 50
###  Level height of the running ways                    ###
###  Default: 3 (FLAT WORLD)                             ###
levelHeight: 3
###  Blocks per tick to handle with (1 tick = 1/20 sec)  ###
###  Be careful, this may result in lags                 ###
###  Default: 1000                                       ###
maxBlocksPerTick: 1000
###  Results to show on one page in lists                ###
###  Default: 5                                          ###
maxResultsPerPage: 5
###  Maximum of plots for one user                       ###
###  Players with permission flatme.moreplots are        ###
###  allowed to build more plots                         ###
###  Default: 1                                          ###
plotsPerUser: 1
###  Days until a plot expires                           ###
###  Default: 60                                         ###
daysPerPlot: 60
###  Costs to extend a plot                              ###
###  Default: 1000                                       ###
extendCost: 1000
###  Auto-update all plots 60 secs after server start    ###
###  Default: true                                       ###
autoUpdate: true
###  Delay in seconds befor a teleport is triggered      ###
###  Players with permission flatme.instantport are      ###
###  allowed to teleport instantly                       ###
###  Default: 3                                          ###
portDelay: 3
