######################################################################################################
###                                                                                                ###
###   FlatMe - Plot Plugin by Steven Meisberger (Sigmaroot Administration)                         ###
###                                                                                                ###
###     Version:     1.0                                                                           ###
###     File:        Basic Configuration                                                           ###
###                                                                                                ###
###     Date:        01.11.2015                                                                    ###
###                                                                                                ###
######################################################################################################
language: en
world: world
plotSize: 50
levelHeight: 3
maxBlocksPerTick: 100
maxResultsPerPage: 5
