name: FlatMe
main: de.sigmaroot.plugins.FlatMe
version: 1.8.6
author: Steven Meisberger
homepage: http://www.sigmaroot.de/
depend: [Essentials, WorldGuard, WorldEdit]
softdepend: [Multiverse-Core]
commands:
  flatme:
    description: "FlatMe Plugin Interface"
    usage: "/flatme <command>"
