name: FlatMe
main: de.sigmaroot.plugins.FlatMe
version: 1.8.8
author: Steven Meisberger
homepage: http://www.sigmaroot.de/
depend: [Essentials, WorldGuard, WorldEdit]
commands:
  flatme:
    description: "FlatMe Plugin Interface"
    usage: "/flatme <command>"
