name: FlatMe
main: de.sigmaroot.plugins.FlatMe
version: 1.5
author: Steven Meisberger
homepage: http://www.sigmaroot.de/
depend: [Essentials, WorldGuard, WorldEdit]
softdepend: [Multiverse-Core]
commands:
  flatme:
    description: "FlatMe Plugin Interface"
    usage: /flatme <params>
    permission: flatme.player
    permission-message: "You don't have the permission to use this command."
