name: FlatMe
main: de.sigmaroot.plugins.FlatMe
version: 1.10.0
author: Steven M.
homepage: http://www.sigmaroot.de/
depend: [Essentials, WorldGuard, WorldEdit]
commands:
  flatme:
    description: "FlatMe Plugin Interface"
    usage: "/flatme <command>"
