name: FlatMe
main: de.sigmaroot.plugins.FlatMe
version: 1.0
author: Steven Meisberger
homepage: http://www.sigmaroot.de/
depend: []
softdepend: []
commands:
  flatme:
    description: -#-
    usage: -#-
    permission: flatme
    permission-message: -#-