package de.sigmaroot.plugins;

public enum QueueTaskType {

	CLEAN_MESSAGE, CONSOLE_MESSAGE, CREATE_AREA_BORDER, CREATE_PLOT_BORDER, CREATE_RUNWAY, ENTITY_REMOVE, REGEN_PLOT, REMOVE_PLOT, REMOVE_REGION, WE_REGEN_PLOT

}
